# 配置文件说明
description: |
  This is the configuration file for the video classification project.
  Use --mode to specify the mode (train, evaluate, or infer) and --config to provide this file's path.

# 数据配置
data:
  input_dirs: data/Celeb-DF-v2
  train_dir: "data/train_videos_v2"               # 训练数据所在的文件夹路径
  train_labels: "data/train_labels_v2.json"       # 训练数据标签文件路径，通常为 JSON 文件或其他格式的标签映射
  val_dir: "data/val_videos_v2"                   # 验证数据所在的文件夹路径
  val_labels: "data/val_labels_v2.json"           # 验证数据标签文件路径
  num_frames: 8                               # 每个视频的帧数
  frame_size: 512                              # 每帧的尺寸 (height, width)

# 模型配置
model:
  num_frames: 8                               # 模型输入的视频帧数
  num_patches: 49                              # 每帧分割成的 patch 数量，越多约注意细节
  d_model: 512                                 # 特征维度
  num_heads: 4                                 # 多头自注意力机制中的头数
  num_layers: 4                                # Transformer 编码层的数量
  dim_feedforward: 2048                        # 前馈神经网络的维度
  num_classes: 2                               # 分类类别数
  save_dir: "models/checkpoints"               # 保存模型检查点的目录
  checkpoint_path: "models/checkpoints/epoch_4.pth"  # 预训练模型权重文件路径

# 训练配置
training:
  batch_size: 1                               # 训练批次大小
  learning_rate: 0.0001                        # 学习率
  epochs: 20                                   # 训练的总轮数
  subset_ratio: 0.7                            # 预训练时采用的数据比例
  patience: 2
  checkpoint_interval: 2                       # 每隔多少个 epoch 保存一次模型检查点

# 评估配置
evaluation:
  batch_size: 1                               # 验证批次大小
  subset_ratio: 1                            # 预训练时采用的数据比例
  metrics: ["accuracy", "precision", "recall", "f1_score", "auc"]  # 需要计算的评估指标

# 推理配置
inference:
  threshold: 0.5                               # 分类阈值 (用于二分类问题)
  input_size: [128, 128]                       # 推理时视频帧的输入尺寸 (height, width)

labels:
  0: "Real"
  1: "Fake"
